[client]
showSidebarNavigation = false

[theme]
font = "sans serif"

[theme.light]
primaryColor = "#0ed176ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#333333"

[theme.light.sidebar]
primaryColor = "#0ed176ff"
backgroundColor = "#e4dbdbff"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#333333"

[theme.dark]
primaryColor = "#0ed176ff"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"

[theme.dark.sidebar]
primaryColor = "#0ed176ff"
backgroundColor = "#161B22"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"